version: '3.2'

networks:
  web:
    external: true
  internal:
    external: false

services:
  lizmap:
    image: jancelin/docker-lizmap:3.2rc6
    restart: on-failure
    volumes:
     - ${PWD}/docker/lizmap/project:/home
     - ${PWD}/docker/lizmap/var:/var/www/websig/lizmap/var
    depends_on:
      - postgis
      - qgiserver
      - redis
    labels:
     traefik.backend: "lizmap"
     traefik.enable: "true"
     traefik.backend: "lizmap"
     traefik.frontend.rule: "Host: lizmap.officinecartografiche.net"
     traefik.docker.network: "web"
    links:
     - qgiserver:qgiserver
     - redis:redis
    networks:
      - internal
      - web
  qgiserver:
    image: kartoza/qgis-server:3.0.3
    hostname: qgiserver
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_CACHE_SIZE: '20'
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_USER: 1000:1000
      ROUTER_HOST: map
      QGIS_PROJECT_FILE: /project/project.qgs
      QGIS_SERVER_LOG_LEVEL: 0
    volumes:
      - ${PWD}/docker/qgiserver/qgis:/srv/projects
      - ${PWD}/docker/qgiserver/etc:/srv/etc:ro
      - ${PWD}/docker/qgiserver/wps-data:/srv/data
    restart: unless-stopped
    labels:
     traefik.backend: "qgiserver"
     traefik.enable: "true"
     traefik.backend: "qgiserver"
     traefik.frontend.rule: "Host: qgiserver.officinecartografiche.net"
     traefik.docker.network: "web"
    networks:
      - internal
      - web 
  redis:
    image: redis:4
    volumes:
      - ${PWD}/docker/redis:/data
    restart: unless-stopped
    networks:
      - internal
      - web
  cloud:
    image: nextcloud:latest
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: nextcloud
      POSTGRES_USER: docker
    labels:
     traefik.backend: "nextcloud"
     traefik.enable: "true"
     traefik.backend: "nextcloud"
     traefik.frontend.rule: "Host: cloud.officinecartografiche.net"
     traefik.docker.network: "web"
    volumes:
      - ${PWD}/docker/nextcloud:/var/www/html
      - ${PWD}/docker/lizmap/project:/data:rw
    networks:
      - internal
      - web
  postgis:
    image: mdillon/postgis
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_USER: docker
      POSTGRES_DBNAME: gis
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - ${PWD}/docker/postgis/postgresql:/var/lib/postgresql
      - ${PWD}/docker/postgis/home/:/home
    networks:
      - internal
      - web
